name: flutter_kependudukan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0 # Updated from 3.0.
  
  #dotenv
  flutter_dotenv: ^5.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Network
  http: ^1.1.0
  internet_connection_checker: ^1.0.0
  webview_flutter: ^4.4.2
  
  # Storage
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # Map related packages
  flutter_map: ^6.0.0 # Updated from 3.1.0
  latlong2: ^0.9.0
  
  # Other utilities
  intl: ^0.18.0
  url_launcher: ^6.3.1

  #image picker
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

